version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: "/"
    rebase-strategy: auto
    allow:
      - dependency-type: all
    schedule:
      interval: daily
