linters:
  enable:
    - gofmt
    - goimports
    - gocyclo
    - revive
    - misspell
    - gocritic
    - govet
    - godot
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 15

  staticcheck:
    go: "1.18"
    checks: ["all"]

  govet:
    enable-all: true
