linters:
  disable-all: true
  enable:
    - errcheck
    - exhaustive
    - gocritic
    - gocyclo
    - godot
    - gofumpt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unused
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 20

  staticcheck:
    go: "1.20"
    checks: ["all"]

  govet:
    enable-all: true
