linters:
  enable:
    - gofmt
    - gocyclo
    - revive
    - misspell
    - gocritic
    - govet
    - godot
  disable:
    # For now, during development because we have some unused sections
    - deadcode
    - unused
    - varcheck

linters-settings:
  gocyclo:
    min-complexity: 15

  staticcheck:
    go: "1.17"
    checks: ["all"]

  govet:
    enable-all: true
