linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - exhaustive
    - gocritic
    - gocyclo
    - godot
    # - gofmt
    # - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unused
    - varcheck
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 20

  staticcheck:
    go: "1.18"
    checks: ["all"]

  govet:
    enable-all: true
