run:
  go: "1.17" # Spok doesn't use generic code, 1.18 some linters are currently broken

linters:
  enable:
    - gofmt
    - goimports
    - gocyclo
    - revive
    - misspell
    - gocritic
    - govet
    - godot
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 15

  staticcheck:
    go: "1.17"
    checks: ["all"]

  govet:
    enable-all: true
