version: 2

project_name: "spok"

before:
  hooks:
    - go install golang.org/x/tools/cmd/stringer@latest
    - go mod tidy
    - go generate ./...
    - go fmt ./...

builds:
  - id: "spok"
    dir: "."
    main: "./cmd/spok"
    binary: "spok"
    ldflags:
      - -s -w
      - -X go.followtheprocess.codes/spok/cli/cmd.version={{.Version}}
      - -X go.followtheprocess.codes/spok/cli/cmd.commit={{.Commit}}
      - -X go.followtheprocess.codes/spok/cli/cmd.buildDate={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm64
    goarm:
      - "7"

homebrew_casks:
  - name: spok
    binary: spok
    directory: Casks
    description: It's a build system Jim, but not as we know it!
    homepage: https://github.com/FollowTheProcess/spok
    conflicts:
      - formula: spok
    commit_author:
      name: Tom Fleet
      email: me@followtheprocess.codes
    repository:
      owner: FollowTheProcess
      name: homebrew-tap
      token: "{{.Env.HOMEBREW_TAP_TOKEN}}"
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/spok"]
          end

archives:
  - id: spok
    name_template: >-
      {{ .ProjectName }}-
      {{- .Version }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

sboms:
  - id: spok
    artifacts: archive
    documents:
      - >-
        {{ .ProjectName }}-
        {{- .Version}}-
        {{- .Os }}-
        {{- if eq .Arch "amd64" }}x86_64
        {{- else if eq .Arch "386" }}i386
        {{- else }}{{ .Arch }}{{ end }}.sbom

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-dev{{ .ShortCommit }}"

changelog:
  # The changelog is handled by release drafter
  disable: true
