ignore:
  - "cmd" # Nothing here but the main.go which just calls cobra run
  - "cli/cmd" # Nothing here but the cobra command declaration which calls app.Run
  - "**/*_string.go" # Stringer generated stuff
  - "logger" # Literally just a wrapper around Zap
