// Code generated by "stringer -type=tokenType -linecomment"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[tokenError-0]
	_ = x[tokenEOF-1]
	_ = x[tokenHash-2]
	_ = x[tokenComment-3]
	_ = x[tokenDeclare-4]
	_ = x[tokenTask-5]
	_ = x[tokenOpenParen-6]
	_ = x[tokenCloseParen-7]
	_ = x[tokenOpenBrace-8]
	_ = x[tokenCloseBrace-9]
	_ = x[tokenOpenBracket-10]
	_ = x[tokenCloseBracket-11]
	_ = x[tokenOutput-12]
}

const _tokenType_name = "ErrorEOF#Comment:=task(){}[]->"

var _tokenType_index = [...]uint8{0, 5, 8, 9, 16, 18, 22, 23, 24, 25, 26, 27, 28, 30}

func (i tokenType) String() string {
	if i < 0 || i >= tokenType(len(_tokenType_index)-1) {
		return "tokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokenType_name[_tokenType_index[i]:_tokenType_index[i+1]]
}
