// Code generated by "stringer -type=Type -linecomment -output=token_string.go"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ERROR-0]
	_ = x[EOF-1]
	_ = x[NEWLINE-2]
	_ = x[COMMENT-3]
	_ = x[HASH-4]
	_ = x[LPAREN-5]
	_ = x[RPAREN-6]
	_ = x[LBRACE-7]
	_ = x[RBRACE-8]
	_ = x[LBRACKET-9]
	_ = x[RBRACKET-10]
	_ = x[QUOTE-11]
	_ = x[COMMA-12]
	_ = x[TASK-13]
	_ = x[STRING-14]
	_ = x[OUTPUT-15]
	_ = x[IDENT-16]
	_ = x[DECLARE-17]
}

const _Type_name = "ERROREOF\\nCOMMENT#(){}[]\",TASKSTRING->IDENT:="

var _Type_index = [...]uint8{0, 5, 8, 10, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 30, 36, 38, 43, 45}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
