// Code generated by "stringer -type=NodeType -output=nodetype_string.go"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NodeComment-0]
	_ = x[NodeIdent-1]
	_ = x[NodeString-2]
	_ = x[NodeInteger-3]
	_ = x[NodeFunction-4]
	_ = x[NodeTask-5]
}

const _NodeType_name = "NodeCommentNodeIdentNodeStringNodeIntegerNodeFunctionNodeTask"

var _NodeType_index = [...]uint8{0, 11, 20, 30, 41, 53, 61}

func (i NodeType) String() string {
	if i < 0 || i >= NodeType(len(_NodeType_index)-1) {
		return "NodeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeType_name[_NodeType_index[i]:_NodeType_index[i+1]]
}
