name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions: {}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
      pages: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Fetch Existing Tags
        run: git fetch --force --tags

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@v0.20.6

      - name: Parse Release Version
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Publish Draft Release
        uses: release-drafter/release-drafter@v6
        with:
          version: ${{ steps.version.outputs.version }}
          publish: true
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: ~> v2
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ github.token }}
          HOMEBREW_TAP_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}

      - name: Generate Binary Attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: dist/*

      - name: Set up Nox
        uses: wntrblm/nox@2025.05.01
        with:
          python-versions: "3.13"

      - name: Deploy Docs to GitHub Pages
        run: nox --non-interactive --session publish
        env:
          GITHUB_TOKEN: ${{ github.token }}
